replicaCount: 2
name: new-deployment
image:
  repository: 112715105011/hello-java-spring-boot
  pullPolicy: IfNotPresent
  tag: latest
  
env:
  environ: true

service:
  type: ClusterIP
  port: 8080
  name: six-test
  targetport: 8080
  
container:
  name: react-ui
  
