apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "oc-deployment.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oc-deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oc-deployment.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            - name: environ
              value: {{ .Values.env.environ | quote }}
            - name: DIRS_AUTH_AID
              valueFrom:
                secretKeyRef:
                  key: aid
                  name: secret
          name: {{ .Values.containers.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
